#ifndef FUNCNAME_H
#define FUNCNAME_H

#define jniRestoreProjectData Java_com_gk969_UltimateImgSpider_WatchdogService_jniRestoreProjectData
#define jniStoreProjectData Java_com_gk969_UltimateImgSpider_WatchdogService_jniStoreProjectData

#define jniGetAshmem Java_com_gk969_UltimateImgSpider_WatchdogService_jniGetAshmem

#define stringFromJNI Java_com_gk969_UltimateImgSpider_SpiderService_stringFromJNI

#define jniSpiderInit Java_com_gk969_UltimateImgSpider_SpiderService_jniSpiderInit
#define jniGetProjectInfoOnStart Java_com_gk969_gallerySimple_AlbumSetLoaderHelper_jniGetProjectInfoOnStart
#define jniAddUrl Java_com_gk969_UltimateImgSpider_SpiderService_jniAddUrl
#define jniSetSrcPageUrl Java_com_gk969_UltimateImgSpider_SpiderService_jniSetSrcPageUrl
#define jniRecvPageTitle Java_com_gk969_UltimateImgSpider_SpiderService_jniRecvPageTitle
#define jniFindNextPageUrl Java_com_gk969_UltimateImgSpider_SpiderService_jniFindNextPageUrl
#define jniFindNextImgUrl Java_com_gk969_UltimateImgSpider_SpiderService_jniFindNextImgUrl
#define jniSaveImgStorageInfo Java_com_gk969_UltimateImgSpider_SpiderService_jniSaveImgStorageInfo


#endif
